### ISSUE TITLE
Request Write access for fkouteib to the Agave Monorepo

### ISSUE THREAD

**Issue by fkouteib** [anza-xyz/contributor-access-policy#11]
### GitHub Username

fkouteib

### Discord ID

pegasus360

### Previously approved Triage access request issue

https://github.com/anza-xyz/contributor-access-policy/issues/12

**Comment by bw-solana** [comment]
I vouch for @fkouteib

**Comment by ilya-bobyr** [comment]
Second for @fkouteib

**Comment by anza-team** [comment]
https://github.com/anza-xyz/contributor-access-policy/actions/runs/9573968041

**Comment by CriesofCarrots** [comment]
@yihau @joeaba  , will this work if there wasn't a Triage request first?

**Comment by joeaba** [comment]
You are right, that's why it's failing.
@fkouteib please open a Triage access issue first

**Comment by fkouteib** [comment]
Thx @joeaba Triage request approved and complete https://github.com/anza-xyz/contributor-access-policy/issues/12. I update the original comment in this PR with the relevant link. Please let me know if I can use this issue for the request, or need to re-file it.
