### ISSUE TITLE
Request Write access for sam0x17 to the Agave Monorepo

### ISSUE THREAD

**Issue by sam0x17** [anza-xyz/contributor-access-policy#17]
### GitHub Username

sam0x17

### Discord ID

sam0x17

### Previously approved Triage access request issue

https://github.com/anza-xyz/contributor-access-policy/issues/16

**Comment by fkouteib** [comment]
I vouch for Sam

**Comment by bw-solana** [comment]
I vouch for Sam

**Comment by anza-team** [comment]
https://github.com/anza-xyz/contributor-access-policy/actions/runs/10478845920
