### ISSUE TITLE
Request Triage access for alexpyattaev to the Agave Monorepo

### ISSUE THREAD

**Issue by alexpyattaev** [anza-xyz/contributor-access-policy#18]
### GitHub Username

alexpyattaev

### Discord ID

Alex[HeadHunter]#2126

**Comment by gregcusack** [comment]
I vouch for Alex

**Comment by gregcusack** [comment]
I support the promotion of @alexpyattaev to Triage so get can get his discord setup

**Comment by alexpyattaev** [comment]
@t-nelson please approve for onboarding process.

**Comment by anza-team** [comment]
https://github.com/anza-xyz/contributor-access-policy/actions/runs/11899998559
