### ISSUE TITLE
Request Write access for alexpyattaev to the Agave Monorepo

### ISSUE THREAD

**Issue by alexpyattaev** [anza-xyz/contributor-access-policy#19]
### GitHub Username

alexpyattaev

### Discord ID

Alex[HeadHunter]#2126

### Previously approved Triage access request issue

https://github.com/anza-xyz/contributor-access-policy/issues/18

**Comment by gregcusack** [comment]
I support the promotion of @alexpyattaev for write access

**Comment by anza-team** [comment]
https://github.com/anza-xyz/contributor-access-policy/actions/runs/11900071378
