### ISSUE TITLE
Request Write access for 2501babe to the Agave Monorepo

### ISSUE THREAD

**Issue by 2501babe** [anza-xyz/contributor-access-policy#6]
### GitHub Username

2501babe

### Discord ID

2501babe

### Previously approved Triage access request issue

https://github.com/solana-labs/contributor-access-policy/issues/68

**Comment by yihau** [comment]
I've added you to another core team but we can still process this one!  I vouch for hana

**Comment by 2501babe** [comment]
oh i opened this because i could have sworn i didnt have permission to merge an agave pr that had an approving reviewer (but i cant check this now because the review has become stale)

**Comment by yihau** [comment]
Oh no, sorry for the misunderstanding. I meant to say that I just added you yesterday 🙈 you should have the permission to merge PR now. let me know if you still have issues 🫡
